
name: Build Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3

      - name: Install Node dependencies
        run: |
            Set-ExecutionPolicy Unrestricted -Force
            iex ((New-Object System.Net.WebClient).DownloadString('https://boxstarter.org/bootstrapper.ps1'))
            get-boxstarter -Force
            Install-BoxstarterPackage https://raw.githubusercontent.com/nodejs/node/HEAD/tools/bootstrap/windows_boxstarter -DisableReboots
            refreshenv
      - name: Install packages
        run: npm i

      - name: Build
        run:  npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
