
name: Build Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        version: ['v22.x', 'v18.x', 'v16.x', 'v20.x', 'v19.x', 'v17.x']
        strategy: [a, b, c]
        architecture: [arm64, x64]
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3

      - name: Install Node dependencies
        run: powershell.exe ./win-setup-env.ps1
      - name: Install packages
        run: npm i

      - name: Build
        run:  npm run build ${{ matrix.version }} ${{ matrix.strategy }} ${{ matrix.architecture }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
